import { createServerFn } from "@tanstack/react-start";
import { generateAIResponse } from "./ai-gateway.server";
import JSZip from "jszip";
import { deployToCloudflare } from "./cloudflare.server";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { rateLimitMiddleware } from "./rate-limit.server";

export const buildAndDeploy = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => {
    const obj = (input ?? {}) as Record<string, unknown>;
    const prompt = typeof obj.prompt === "string" ? obj.prompt.slice(0, 4000) : "";
    const planText = typeof obj.planText === "string" ? obj.planText.slice(0, 12000) : "";
    if (!prompt) throw new Error("Prompt required.");
    return { prompt, planText };
  })
  .handler(async ({ data, context }) => {
    const { prompt, planText } = data;
    const { userId } = context as any;

    // Step 1: Generate the full-stack app contents
    const files: Array<{ name: string; content: string }> = [];

    // 1. Generate README.md
    const readmeContent = await generateREADME(prompt, planText);
    files.push({ name: "README.md", content: readmeContent });

    // 2. Generate package.json
    const packageJsonContent = await generatePackageJson(prompt, planText);
    files.push({ name: "package.json", content: packageJsonContent });

    // 3. Generate tsconfig.json
    const tsconfigContent = await generateTsconfig(prompt, planText);
    files.push({ name: "tsconfig.json", content: tsconfigContent });

    // 4. Generate vite.config.ts
    const viteConfigContent = await generateViteConfig(prompt, planText);
    files.push({ name: "vite.config.ts", content: viteConfigContent });

    // 5. Generate Supabase migration
    const migrationContent = await generateSupabaseMigration(prompt, planText);
    files.push({ name: "supabase/migrations/20260613000000_init.sql", content: migrationContent });

    // 6. Generate src/lib/supabase.ts
    const supabaseClientContent = await generateSupabaseClient(prompt, planText);
    files.push({ name: "src/lib/supabase.ts", content: supabaseClientContent });

    // 7. Generate src/routes/index.tsx (home page)
    const homePageContent = await generateHomePage(prompt, planText);
    files.push({ name: "src/routes/index.tsx", content: homePageContent });

    // Generate the zip as base64 for download
    const zip = new JSZip();
    files.forEach((file) => {
      zip.file(file.name, file.content);
    });
    const zipBase64 = await zip.generateAsync({ type: "base64" });
    const downloadUrl = `data:application/zip;base64,${zipBase64}`;

    // Step 2: Deploy to Cloudflare Pages
    const projectSlug = prompt
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .substring(0, 50);

    const deploymentResult = await deployToCloudflare({
      projectSlug,
      userId,
      files,
    });

    return {
      success: true,
      downloadUrl,
      deploymentUrl: deploymentResult.deploymentUrl,
      fileSizeMb: (zipBase64.length * 0.75) / (1024 * 1024),
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    };
  });

async function generateREADME(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's documentation writer. Generate a clear, concise README.md for a full-stack TanStack Start application based on the user's prompt and plan.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate a README.md that includes:
- Project title and description
- Features
- Tech stack
- Setup instructions (npm install, npx supabase start, etc.)
- Deployment instructions
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 1500,
  });
  return content.trim();
}

async function generatePackageJson(prompt: string, planText: string): Promise<string> {
  return JSON.stringify(
    {
      name: "generated-app",
      version: "1.0.0",
      description: "A full-stack TanStack Start application generated by Signhify AI",
      main: "index.js",
      scripts: {
        dev: "vite dev",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        "@tanstack/react-query": "^5.83.0",
        "@tanstack/react-router": "^1.168.25",
        "@tanstack/react-start": "^1.167.50",
        "@supabase/supabase-js": "^2.107.0",
        react: "^19.2.0",
        "react-dom": "^19.2.0",
      },
      devDependencies: {
        "@types/react": "^19.2.0",
        "@types/react-dom": "^19.2.0",
        "@vitejs/plugin-react": "^5.0.4",
        typescript: "^5.8.3",
        vite: "^7.3.1",
      },
    },
    null,
    2,
  );
}

async function generateTsconfig(prompt: string, planText: string): Promise<string> {
  return JSON.stringify(
    {
      include: ["src/**/*.ts", "src/**/*.tsx", "vite.config.ts"],
      compilerOptions: {
        target: "ES2022",
        jsx: "react-jsx",
        module: "ESNext",
        lib: ["ES2022", "DOM", "DOM.Iterable"],
        types: ["vite/client"],
        moduleResolution: "Bundler",
        allowImportingTsExtensions: true,
        verbatimModuleSyntax: false,
        noEmit: true,
        strict: true,
        skipLibCheck: true,
        paths: {
          "@/*": ["./src/*"],
        },
      },
    },
    null,
    2,
  );
}

async function generateViteConfig(prompt: string, planText: string): Promise<string> {
  return `import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
});
`;
}

async function generateSupabaseMigration(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's database architect. Generate a Supabase migration SQL file that creates the necessary tables for the application based on the user's prompt and plan. The SQL should be safe to run in a new Supabase project. Use proper data types, constraints, and indexes.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate a Supabase migration SQL that includes:
- Tables for the core entities described in the plan
- Primary keys, foreign keys, and constraints
- Row Level Security (RLS) policies if needed
- Indexes for performance
- Example: if the plan is for a task manager, create tables for tasks, users, etc.
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}

async function generateSupabaseClient(prompt: string, planText: string): Promise<string> {
  // We can generate a supabase client similar to the existing one but with placeholders for URL and key
  return `import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Missing Supabase environment variables");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;
}

async function generateHomePage(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's frontend engineer. Generate a TanStack Start route file for the home page (src/routes/index.tsx) based on the user's prompt and plan. The component should be functional, use React 19, TanStack Router, and include any necessary data fetching.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate the content for src/routes/index.tsx that includes:
- A functional component that serves as the home page
- Use of TanStack Router components if needed (like Link, Navigate)
- Data fetching with TanStack Query (if applicable)
- UI elements described in the plan (from UI/UX Designer and Frontend Engineer sections)
- Tailwind CSS classes for styling
- Export the component as the default
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}
