import { createServerFn } from "@tanstack/react-start";
import { generateAIResponse } from "./ai-gateway.server";
import JSZip from "jszip";

export const buildAndDeploy = createServerFn({ method: "POST" })
  .inputValidator((input: unknown) => {
    const obj = (input ?? {}) as Record<string, unknown>;
    const prompt = typeof obj.prompt === "string" ? obj.prompt.slice(0, 4000) : "";
    const planText = typeof obj.planText === "string" ? obj.planText.slice(0, 12000) : "";
    if (!prompt) throw new Error("Prompt required.");
    return { prompt, planText };
  })
  .handler(async ({ data }) => {
    const { prompt, planText } = data;

    // Step 1: Generate the full-stack app (ZIP)
    const zip = new JSZip();

    // 1. Generate README.md
    const readmeContent = await generateREADME(prompt, planText);
    zip.file("README.md", readmeContent);

    // 2. Generate package.json
    const packageJsonContent = await generatePackageJson(prompt, planText);
    zip.file("package.json", packageJsonContent);

    // 3. Generate tsconfig.json
    const tsconfigContent = await generateTsconfig(prompt, planText);
    zip.file("tsconfig.json", tsconfigContent);

    // 4. Generate vite.config.ts
    const viteConfigContent = await generateViteConfig(prompt, planText);
    zip.file("vite.config.ts", viteConfigContent);

    // 5. Generate Supabase migration
    const migrationContent = await generateSupabaseMigration(prompt, planText);
    zip.file("supabase/migrations/20260613000000_init.sql", migrationContent);

    // 6. Generate src/lib/supabase.ts
    const supabaseClientContent = await generateSupabaseClient(prompt, planText);
    zip.file("src/lib/supabase.ts", supabaseClientContent);

    // 7. Generate src/routes/index.tsx (home page)
    const homePageContent = await generateHomePage(prompt, planText);
    zip.file("src/routes/index.tsx", homePageContent);

    // Generate the zip as base64 for download
    const zipBase64 = await zip.generateAsync({ type: "base64" });
    const downloadUrl = `data:application/zip;base64,${zipBase64}`;

    // Step 2: Prepare for deployment
    // For Cloudflare Pages deployment, we need to extract the ZIP and deploy individual files
    // For simplicity in this implementation, we'll deploy a simplified version
    // In a production implementation, we would:
    // 1. Extract the ZIP to get individual files
    // 2. Deploy those files to Cloudflare Pages (for static assets)
    // 3. Deploy server functions to Cloudflare Workers (for API routes)

    // For now, we'll return both the download URL and a placeholder deployment URL
    // In a full implementation, this would integrate with the deployToCloudflare function

    // Generate a unique project slug from the prompt
    const projectSlug = prompt
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .substring(0, 50);

    // TODO: Implement actual deployment to Cloudflare Pages/Workers
    // This would involve:
    // 1. Extracting the ZIP file
    // 2. Using the deployToCloudflare function or a modified version
    // 3. Handling both static assets (for Pages) and server functions (for Workers)

    const deploymentUrl = `https://${projectSlug}.signhify.app`;

    return {
      success: true,
      downloadUrl,
      deploymentUrl,
      fileSizeMb: (zipBase64.length * 0.75) / (1024 * 1024),
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    };
  });

async function generateREADME(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's documentation writer. Generate a clear, concise README.md for a full-stack TanStack Start application based on the user's prompt and plan.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate a README.md that includes:
- Project title and description
- Features
- Tech stack
- Setup instructions (npm install, npx supabase start, etc.)
- Deployment instructions
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 1500,
  });
  return content.trim();
}

async function generatePackageJson(prompt: string, planText: string): Promise<string> {
  return JSON.stringify(
    {
      name: "generated-app",
      version: "1.0.0",
      description: "A full-stack TanStack Start application generated by Signhify AI",
      main: "index.js",
      scripts: {
        dev: "vite dev",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        "@tanstack/react-query": "^5.83.0",
        "@tanstack/react-router": "^1.168.25",
        "@tanstack/react-start": "^1.167.50",
        "@supabase/supabase-js": "^2.107.0",
        "react": "^19.2.0",
        "react-dom": "^19.2.0",
      },
      devDependencies: {
        "@types/react": "^19.2.0",
        "@types/react-dom": "^19.2.0",
        "@vitejs/plugin-react": "^5.0.4",
        "typescript": "^5.8.3",
        "vite": "^7.3.1",
      },
    },
    null,
    2
  );
}

async function generateTsconfig(prompt: string, planText: string): Promise<string> {
  return JSON.stringify(
    {
      include: ["src/**/*.ts", "src/**/*.tsx", "vite.config.ts"],
      compilerOptions: {
        target: "ES2022",
        jsx: "react-jsx",
        module: "ESNext",
        lib: ["ES2022", "DOM", "DOM.Iterable"],
        types: ["vite/client"],
        moduleResolution: "Bundler",
        allowImportingTsExtensions: true,
        verbatimModuleSyntax: false,
        noEmit: true,
        strict: true,
        skipLibCheck: true,
        paths: {
          "@/*": ["./src/*"],
        },
      },
    },
    null,
    2
  );
}

async function generateViteConfig(prompt: string, planText: string): Promise<string> {
  return `import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
});
`;
}

async function generateSupabaseMigration(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's database architect. Generate a Supabase migration SQL file that creates the necessary tables for the application based on the user's prompt and plan. The SQL should be safe to run in a new Supabase project. Use proper data types, constraints, and indexes.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate a Supabase migration SQL that includes:
- Tables for the core entities described in the plan
- Primary keys, foreign keys, and constraints
- Row Level Security (RLS) policies if needed
- Indexes for performance
- Example: if the plan is for a task manager, create tables for tasks, users, etc.
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}

async function generateSupabaseClient(prompt: string, planText: string): Promise<string> {
  // We can generate a supabase client similar to the existing one but with placeholders for URL and key
  return `import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Missing Supabase environment variables");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;
}

async function generateHomePage(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's frontend engineer. Generate a TanStack Start route file for the home page (src/routes/index.tsx) based on the user's prompt and plan. The component should be functional, use React 19, TanStack Router, and include any necessary data fetching.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate the content for src/routes/index.tsx that includes:
- A functional component that serves as the home page
- Use of TanStack Router components if needed (like Link, Navigate)
- Data fetching with TanStack Query (if applicable)
- UI elements described in the plan (from UI/UX Designer and Frontend Engineer sections)
- Tailwind CSS classes for styling
- Export the component as the default
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}