import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { generateAIResponse } from "./ai-gateway.server";
import { resolveAIAccess } from "./ai-access.server";
import { withByokKeys } from "./byok-middleware";
import JSZip from "jszip";

export const buildFullStackApp = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth, withByokKeys])
  .inputValidator((input: unknown) => {
    const obj = (input ?? {}) as Record<string, unknown>;
    const prompt = typeof obj.prompt === "string" ? obj.prompt.slice(0, 4000) : "";
    const planText = typeof obj.planText === "string" ? obj.planText.slice(0, 12000) : "";
    if (!prompt) throw new Error("Prompt required.");
    return { prompt, planText };
  })
  .handler(async ({ data, context }) => {
    const { prompt, planText } = data;
    const { supabase, userId, claims } = context as {
      supabase: any;
      userId: string;
      claims?: { email?: string | null };
    };
    const byokClientKeys = (context as { byokClientKeys?: Record<string, string> }).byokClientKeys;
    // Gate before doing any AI work: free users must BYOK, paid/admin proceed.
    // BYOKRequiredError bubbles up to the client with an actionable message.
    await resolveAIAccess({ supabase, userId, email: claims?.email ?? null, byokClientKeys });

    // We'll generate the file tree step by step
    const zip = new JSZip();

    // 1. Generate README.md
    const readmeContent = await generateREADME(prompt, planText);
    zip.file("README.md", readmeContent);

    // 2. Generate package.json
    const packageJsonContent = await generatePackageJson(prompt, planText);
    zip.file("package.json", packageJsonContent);

    // 3. Generate tsconfig.json
    const tsconfigContent = await generateTsconfig(prompt, planText);
    zip.file("tsconfig.json", tsconfigContent);

    // 4. Generate vite.config.ts
    const viteConfigContent = await generateViteConfig(prompt, planText);
    zip.file("vite.config.ts", viteConfigContent);

    // 5. Generate Supabase migration
    const migrationContent = await generateSupabaseMigration(prompt, planText);
    zip.file("supabase/migrations/20260613000000_init.sql", migrationContent);

    // 6. Generate src/lib/supabase.ts
    const supabaseClientContent = await generateSupabaseClient(prompt, planText);
    zip.file("src/lib/supabase.ts", supabaseClientContent);

    // 7. Generate src/routes/index.tsx (home page)
    const homePageContent = await generateHomePage(prompt, planText);
    zip.file("src/routes/index.tsx", homePageContent);

    // 8. Generate src/routes/items/ (if applicable)
    // We'll check if the plan suggests a list of items
    const { itemsRoute, itemsApi } = await generateItemsCRUD(prompt, planText);
    if (itemsRoute) {
      zip.file("src/routes/items/index.tsx", itemsRoute);
    }
    if (itemsApi) {
      zip.file("src/routes/items/$itemId.tsx", itemsApi);
    }

    // 9. Generate src/lib/functions/items.server.ts
    const itemsServerContent = await generateItemsServer(prompt, planText);
    zip.file("src/lib/functions/items.server.ts", itemsServerContent);

    // Generate the zip as base64
    const zipBase64 = await zip.generateAsync({ type: "base64" });
    const downloadUrl = `data:application/zip;base64,${zipBase64}`;

    return {
      success: true,
      downloadUrl,
      fileSizeMb: (zipBase64.length * 0.75) / (1024 * 1024),
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    };
  });

async function generateREADME(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's documentation writer. Generate a clear, concise README.md for a full-stack TanStack Start application based on the user's prompt and plan.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate a README.md that includes:
- Project title and description
- Features
- Tech stack
- Setup instructions (npm install, npx supabase start, etc.)
- Deployment instructions
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 1500,
  });
  return content.trim();
}

async function generatePackageJson(prompt: string, planText: string): Promise<string> {
  // We'll generate a package.json similar to the current one but maybe simplified
  // For now, we'll return a static one that matches the current dependencies
  // We can use AI to customize it based on the plan, but for simplicity, we'll use a template.
  return JSON.stringify(
    {
      name: "generated-app",
      version: "1.0.0",
      description: "A full-stack TanStack Start application generated by Signhify AI",
      main: "index.js",
      scripts: {
        dev: "vite dev",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        "@tanstack/react-query": "^5.83.0",
        "@tanstack/react-router": "^1.168.25",
        "@tanstack/react-start": "^1.167.50",
        "@supabase/supabase-js": "^2.107.0",
        react: "^19.2.0",
        "react-dom": "^19.2.0",
      },
      devDependencies: {
        "@types/react": "^19.2.0",
        "@types/react-dom": "^19.2.0",
        "@vitejs/plugin-react": "^5.0.4",
        typescript: "^5.8.3",
        vite: "^7.3.1",
      },
    },
    null,
    2,
  );
}

async function generateTsconfig(prompt: string, planText: string): Promise<string> {
  return JSON.stringify(
    {
      include: ["src/**/*.ts", "src/**/*.tsx", "vite.config.ts"],
      compilerOptions: {
        target: "ES2022",
        jsx: "react-jsx",
        module: "ESNext",
        lib: ["ES2022", "DOM", "DOM.Iterable"],
        types: ["vite/client"],
        moduleResolution: "Bundler",
        allowImportingTsExtensions: true,
        verbatimModuleSyntax: false,
        noEmit: true,
        strict: true,
        skipLibCheck: true,
        paths: {
          "@/*": ["./src/*"],
        },
      },
    },
    null,
    2,
  );
}

async function generateViteConfig(prompt: string, planText: string): Promise<string> {
  return `import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
});
`;
}

async function generateSupabaseMigration(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's database architect. Generate a Supabase migration SQL file that creates the necessary tables for the application based on the user's prompt and plan. The SQL should be safe to run in a new Supabase project. Use proper data types, constraints, and indexes.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate a Supabase migration SQL that includes:
- Tables for the core entities described in the plan
- Primary keys, foreign keys, and constraints
- Row Level Security (RLS) policies if needed
- Indexes for performance
- Example: if the plan is for a task manager, create tables for tasks, users, etc.
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}

async function generateSupabaseClient(prompt: string, planText: string): Promise<string> {
  // We can generate a supabase client similar to the existing one but with placeholders for URL and key
  return `import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Missing Supabase environment variables");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;
}

async function generateHomePage(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's frontend engineer. Generate a TanStack Start route file for the home page (src/routes/index.tsx) based on the user's prompt and plan. The component should be functional, use React 19, TanStack Router, and include any necessary data fetching.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate the content for src/routes/index.tsx that includes:
- A functional component that serves as the home page
- Use of TanStack Router components if needed (like Link, Navigate)
- Data fetching with TanStack Query (if applicable)
- UI elements described in the plan (from UI/UX Designer and Frontend Engineer sections)
- Tailwind CSS classes for styling
- Export the component as the default
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}

async function generateItemsCRUD(
  prompt: string,
  planText: string,
): Promise<{
  itemsRoute?: string;
  itemsApi?: string;
}> {
  // We'll use the AI to decide if a CRUD for items is needed and generate the files
  const SYSTEM = `You are Signhify AI's full-stack engineer. Based on the user's prompt and plan, determine if a CRUD interface for a resource (like items, tasks, etc.) is appropriate. If yes, generate the TanStack Start route files for:
  1. src/routes/items/index.tsx (list and create)
  2. src/routes/items/\$itemId.tsx (detail, update, delete)
  If not, return empty strings for both.
  `;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

If the plan describes a collection of items (e.g., tasks, products, users) that need to be created, read, updated, deleted, then generate the two files. Otherwise, indicate that no CRUD is needed.
  `;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });

  // We expect the AI to return a JSON object with the two file contents or null
  try {
    const parsed = JSON.parse(content);
    return {
      itemsRoute: parsed.itemsRoute || undefined,
      itemsApi: parsed.itemsApi || undefined,
    };
  } catch {
    // If not JSON, assume no CRUD
    return { itemsRoute: undefined, itemsApi: undefined };
  }
}

async function generateItemsServer(prompt: string, planText: string): Promise<string> {
  const SYSTEM = `You are Signhify AI's backend engineer. Generate a Supabase server function file (src/lib/functions/items.server.ts) that provides CRUD operations for the items resource based on the user's prompt and plan. Use the Supabase JS client.`;
  const user = `
User prompt:
${prompt}

Plan context:
${planText}

Generate the content for src/lib/functions/items.server.ts that includes:
- Functions to list items, create item, get item by id, update item, delete item
- Proper error handling
- Use of the supabase client from ~/lib/supabase
- Export each function
`;
  const content = await generateAIResponse({
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: user },
    ],
    temperature: 0.6,
    max_tokens: 2000,
  });
  return content.trim();
}
