import { createFileRoute } from "@tanstack/react-router";
import { Breadcrumbs } from "@/components/Breadcrumbs";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service & Engagement Agreement — Signhify Studio" },
      {
        name: "description",
        content:
          "Terms governing the use of signhify.dpdns.org, the Signhify studio engagement and the Signhify AI early-access program.",
      },
      { property: "og:title", content: "Terms of Service & Engagement Agreement — Signhify Studio" },
      { property: "og:url", content: "https://signhify.dpdns.org/terms" },
    ],
    links: [{ rel: "canonical", href: "https://signhify.dpdns.org/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <article className="pt-32 pb-24 mx-auto max-w-3xl px-6 prose prose-invert prose-headings:font-display">
      <Breadcrumbs items={[{ label: "Terms of Service", to: "/terms" }]} />
      <div className="text-xs uppercase tracking-[0.25em] text-primary mb-3">Legal</div>
      <h1 className="font-display text-5xl font-black">Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: June 5, 2026</p>

      <h2>1. Acceptance</h2>
      <p>
        By using <a href="https://signhify.dpdns.org">signhify.dpdns.org</a> or any Signhify product, you
        agree to these terms. If you do not agree, do not use the service.
      </p>

      <h2>2. Studio engagements</h2>
      <p>
        Builds delivered by Signhify are governed by a separate Statement of Work signed with the
        client. These terms cover only the website, the contact wizard and the Signhify AI waitlist.
      </p>

      <h2>3. Signhify AI preview</h2>
      <p>
        Signhify AI is in preview. Outputs are generated by AI models and may contain errors. You
        are responsible for reviewing anything you deploy. We provide no warranty of fitness for a
        particular purpose.
      </p>

      <h2>4. Acceptable use</h2>
      <ul>
        <li>No scraping, reselling or republishing site content without written permission.</li>
        <li>No abusive, illegal or rights-infringing prompts on Signhify AI.</li>
        <li>No attempting to exfiltrate other users&rsquo; data.</li>
      </ul>

      <h2>5. Intellectual property</h2>
      <p>
        The Signhify name, logo and site design are © Signhify. Open-source code we publish is
        governed by its own license file.
      </p>

      <h2>6. Liability</h2>
      <p>
        To the maximum extent permitted by law, Signhify is not liable for indirect or consequential
        damages arising from your use of the site or AI preview. Our total liability is capped at
        fees you have paid us in the prior 3 months (which is zero for the free site/waitlist).
      </p>

      <h2>7. Governing law</h2>
      <p>Indian law. Courts at Patna, Bihar have exclusive jurisdiction.</p>

      <h2>8. Contact</h2>
      <p>
        Questions? <a href="mailto:Piyushrajsingh092@gmail.com">Piyushrajsingh092@gmail.com</a>.
      </p>
    </article>
  );
}
