/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiSourcesRouteImport } from './routes/api/sources'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as ApiCampaignsIdRouteImport } from './routes/api/campaigns.$id'
import { Route as ApiLeadsIdRouteImport } from './routes/api/leads.$id'
import { Route as ApiSourcesIdRouteImport } from './routes/api/sources.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesRoute = ApiSourcesRouteImport.update({
  id: '/api/sources',
  path: '/api/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CampaignsRoute,
} as any)
const ApiCampaignsIdRoute = ApiCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCampaignsRoute,
} as any)
const ApiLeadsIdRoute = ApiLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiSourcesIdRoute = ApiSourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/sources': typeof ApiSourcesRouteWithChildren
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/sources/$id': typeof ApiSourcesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/sources': typeof ApiSourcesRouteWithChildren
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/sources/$id': typeof ApiSourcesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/sources': typeof ApiSourcesRouteWithChildren
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/sources/$id': typeof ApiSourcesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/inbox'
    | '/leads'
    | '/settings'
    | '/sources'
    | '/unsubscribe'
    | '/api/campaigns'
    | '/api/dashboard'
    | '/api/inbox'
    | '/api/leads'
    | '/api/settings'
    | '/api/sources'
    | '/api/unsubscribe'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/api/campaigns/$id'
    | '/api/leads/$id'
    | '/api/sources/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/inbox'
    | '/leads'
    | '/settings'
    | '/sources'
    | '/unsubscribe'
    | '/api/campaigns'
    | '/api/dashboard'
    | '/api/inbox'
    | '/api/leads'
    | '/api/settings'
    | '/api/sources'
    | '/api/unsubscribe'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/api/campaigns/$id'
    | '/api/leads/$id'
    | '/api/sources/$id'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/inbox'
    | '/leads'
    | '/settings'
    | '/sources'
    | '/unsubscribe'
    | '/api/campaigns'
    | '/api/dashboard'
    | '/api/inbox'
    | '/api/leads'
    | '/api/settings'
    | '/api/sources'
    | '/api/unsubscribe'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/api/campaigns/$id'
    | '/api/leads/$id'
    | '/api/sources/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  InboxRoute: typeof InboxRoute
  LeadsRoute: typeof LeadsRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiCampaignsRoute: typeof ApiCampaignsRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiLeadsRoute: typeof ApiLeadsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiSourcesRoute: typeof ApiSourcesRouteWithChildren
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources': {
      id: '/api/sources'
      path: '/api/sources'
      fullPath: '/api/sources'
      preLoaderRoute: typeof ApiSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/api/campaigns/$id': {
      id: '/api/campaigns/$id'
      path: '/$id'
      fullPath: '/api/campaigns/$id'
      preLoaderRoute: typeof ApiCampaignsIdRouteImport
      parentRoute: typeof ApiCampaignsRoute
    }
    '/api/leads/$id': {
      id: '/api/leads/$id'
      path: '/$id'
      fullPath: '/api/leads/$id'
      preLoaderRoute: typeof ApiLeadsIdRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/sources/$id': {
      id: '/api/sources/$id'
      path: '/$id'
      fullPath: '/api/sources/$id'
      preLoaderRoute: typeof ApiSourcesIdRouteImport
      parentRoute: typeof ApiSourcesRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface ApiCampaignsRouteChildren {
  ApiCampaignsIdRoute: typeof ApiCampaignsIdRoute
}

const ApiCampaignsRouteChildren: ApiCampaignsRouteChildren = {
  ApiCampaignsIdRoute: ApiCampaignsIdRoute,
}

const ApiCampaignsRouteWithChildren = ApiCampaignsRoute._addFileChildren(
  ApiCampaignsRouteChildren,
)

interface ApiLeadsRouteChildren {
  ApiLeadsIdRoute: typeof ApiLeadsIdRoute
}

const ApiLeadsRouteChildren: ApiLeadsRouteChildren = {
  ApiLeadsIdRoute: ApiLeadsIdRoute,
}

const ApiLeadsRouteWithChildren = ApiLeadsRoute._addFileChildren(
  ApiLeadsRouteChildren,
)

interface ApiSourcesRouteChildren {
  ApiSourcesIdRoute: typeof ApiSourcesIdRoute
}

const ApiSourcesRouteChildren: ApiSourcesRouteChildren = {
  ApiSourcesIdRoute: ApiSourcesIdRoute,
}

const ApiSourcesRouteWithChildren = ApiSourcesRoute._addFileChildren(
  ApiSourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  InboxRoute: InboxRoute,
  LeadsRoute: LeadsRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiCampaignsRoute: ApiCampaignsRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiLeadsRoute: ApiLeadsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiSourcesRoute: ApiSourcesRouteWithChildren,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
