/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SprintRouteImport } from './routes/sprint'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrollStudioIndexRouteImport } from './routes/scroll-studio/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as StudioSpikeRouteImport } from './routes/studio.spike'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as MarketplaceSuccessRouteImport } from './routes/marketplace.success'
import { Route as MarketplaceSellRouteImport } from './routes/marketplace.sell'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProjectsNewRouteImport } from './routes/app/projects/new'
import { Route as AppProjectsIdRouteImport } from './routes/app/projects/$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AiShareIdRouteImport } from './routes/ai.share.$id'
import { Route as AppProjectsIdAnalyticsRouteImport } from './routes/app/projects/$id.analytics'
import { Route as AppProjectsIdRunsRunIdRouteImport } from './routes/app/projects/$id/runs/$runId'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintRoute = SprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollStudioIndexRoute = ScrollStudioIndexRouteImport.update({
  id: '/scroll-studio/',
  path: '/scroll-studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSpikeRoute = StudioSpikeRouteImport.update({
  id: '/studio/spike',
  path: '/studio/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const MarketplaceSuccessRoute = MarketplaceSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSellRoute = MarketplaceSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/app/projects/new',
  path: '/app/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/app/projects/$id',
  path: '/app/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AiShareIdRoute = AiShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => AiRoute,
} as any)
const AppProjectsIdAnalyticsRoute = AppProjectsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdRunsRunIdRoute = AppProjectsIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/publish': typeof PublishRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sprint': typeof SprintRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/app/settings': typeof AppSettingsRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/marketplace/success': typeof MarketplaceSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/studio/spike': typeof StudioSpikeRoute
  '/app/': typeof AppIndexRoute
  '/scroll-studio/': typeof ScrollStudioIndexRoute
  '/ai/share/$id': typeof AiShareIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/$id/analytics': typeof AppProjectsIdAnalyticsRoute
  '/app/projects/$id/runs/$runId': typeof AppProjectsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/publish': typeof PublishRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sprint': typeof SprintRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/app/settings': typeof AppSettingsRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/marketplace/success': typeof MarketplaceSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/studio/spike': typeof StudioSpikeRoute
  '/app': typeof AppIndexRoute
  '/scroll-studio': typeof ScrollStudioIndexRoute
  '/ai/share/$id': typeof AiShareIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/$id/analytics': typeof AppProjectsIdAnalyticsRoute
  '/app/projects/$id/runs/$runId': typeof AppProjectsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/publish': typeof PublishRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sprint': typeof SprintRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/app/settings': typeof AppSettingsRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/marketplace/success': typeof MarketplaceSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/studio/spike': typeof StudioSpikeRoute
  '/app/': typeof AppIndexRoute
  '/scroll-studio/': typeof ScrollStudioIndexRoute
  '/ai/share/$id': typeof AiShareIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/$id/analytics': typeof AppProjectsIdAnalyticsRoute
  '/app/projects/$id/runs/$runId': typeof AppProjectsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/book'
    | '/contact'
    | '/help'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/publish'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/sprint'
    | '/templates'
    | '/terms'
    | '/vision'
    | '/app/settings'
    | '/marketplace/sell'
    | '/marketplace/success'
    | '/projects/$slug'
    | '/studio/spike'
    | '/app/'
    | '/scroll-studio/'
    | '/ai/share/$id'
    | '/api/public/health'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/projects/$id/analytics'
    | '/app/projects/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/book'
    | '/contact'
    | '/help'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/publish'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/sprint'
    | '/templates'
    | '/terms'
    | '/vision'
    | '/app/settings'
    | '/marketplace/sell'
    | '/marketplace/success'
    | '/projects/$slug'
    | '/studio/spike'
    | '/app'
    | '/scroll-studio'
    | '/ai/share/$id'
    | '/api/public/health'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/projects/$id/analytics'
    | '/app/projects/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai'
    | '/book'
    | '/contact'
    | '/help'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/publish'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/sprint'
    | '/templates'
    | '/terms'
    | '/vision'
    | '/app/settings'
    | '/marketplace/sell'
    | '/marketplace/success'
    | '/projects/$slug'
    | '/studio/spike'
    | '/app/'
    | '/scroll-studio/'
    | '/ai/share/$id'
    | '/api/public/health'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/projects/$id/analytics'
    | '/app/projects/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PublishRoute: typeof PublishRoute
  RoadmapRoute: typeof RoadmapRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SprintRoute: typeof SprintRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  VisionRoute: typeof VisionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  StudioSpikeRoute: typeof StudioSpikeRoute
  AppIndexRoute: typeof AppIndexRoute
  ScrollStudioIndexRoute: typeof ScrollStudioIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint': {
      id: '/sprint'
      path: '/sprint'
      fullPath: '/sprint'
      preLoaderRoute: typeof SprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-studio/': {
      id: '/scroll-studio/'
      path: '/scroll-studio'
      fullPath: '/scroll-studio/'
      preLoaderRoute: typeof ScrollStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/spike': {
      id: '/studio/spike'
      path: '/studio/spike'
      fullPath: '/studio/spike'
      preLoaderRoute: typeof StudioSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/marketplace/success': {
      id: '/marketplace/success'
      path: '/success'
      fullPath: '/marketplace/success'
      preLoaderRoute: typeof MarketplaceSuccessRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/sell': {
      id: '/marketplace/sell'
      path: '/sell'
      fullPath: '/marketplace/sell'
      preLoaderRoute: typeof MarketplaceSellRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/app/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/app/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/share/$id': {
      id: '/ai/share/$id'
      path: '/share/$id'
      fullPath: '/ai/share/$id'
      preLoaderRoute: typeof AiShareIdRouteImport
      parentRoute: typeof AiRoute
    }
    '/app/projects/$id/analytics': {
      id: '/app/projects/$id/analytics'
      path: '/analytics'
      fullPath: '/app/projects/$id/analytics'
      preLoaderRoute: typeof AppProjectsIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/app/projects/$id/runs/$runId': {
      id: '/app/projects/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/app/projects/$id/runs/$runId'
      preLoaderRoute: typeof AppProjectsIdRunsRunIdRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
  }
}

interface AiRouteChildren {
  AiShareIdRoute: typeof AiShareIdRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiShareIdRoute: AiShareIdRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceSellRoute: typeof MarketplaceSellRoute
  MarketplaceSuccessRoute: typeof MarketplaceSuccessRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSellRoute: MarketplaceSellRoute,
  MarketplaceSuccessRoute: MarketplaceSuccessRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface AppProjectsIdRouteChildren {
  AppProjectsIdAnalyticsRoute: typeof AppProjectsIdAnalyticsRoute
  AppProjectsIdRunsRunIdRoute: typeof AppProjectsIdRunsRunIdRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdAnalyticsRoute: AppProjectsIdAnalyticsRoute,
  AppProjectsIdRunsRunIdRoute: AppProjectsIdRunsRunIdRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PublishRoute: PublishRoute,
  RoadmapRoute: RoadmapRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SprintRoute: SprintRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  VisionRoute: VisionRoute,
  AppSettingsRoute: AppSettingsRoute,
  StudioSpikeRoute: StudioSpikeRoute,
  AppIndexRoute: AppIndexRoute,
  ScrollStudioIndexRoute: ScrollStudioIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
