/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SprintRouteImport } from './routes/sprint'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintRoute = SprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sprint': typeof SprintRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sprint': typeof SprintRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sprint': typeof SprintRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/book'
    | '/contact'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/sprint'
    | '/templates'
    | '/terms'
    | '/vision'
    | '/projects/$slug'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/book'
    | '/contact'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/sprint'
    | '/templates'
    | '/terms'
    | '/vision'
    | '/projects/$slug'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai'
    | '/book'
    | '/contact'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/sprint'
    | '/templates'
    | '/terms'
    | '/vision'
    | '/projects/$slug'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SprintRoute: typeof SprintRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  VisionRoute: typeof VisionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint': {
      id: '/sprint'
      path: '/sprint'
      fullPath: '/sprint'
      preLoaderRoute: typeof SprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  MarketplaceRoute: MarketplaceRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SprintRoute: SprintRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  VisionRoute: VisionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
